name: "Build"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix build -L
    - run: nix flake check
    - name: save bit and svf file
      uses: actions/upload-artifact@v4.3.3
      with:
        path: build/stm_sys_board.bit
              build/stm_sys_board.svf
  
          
